---
- hosts: all
  name: Install Ansible Tower
  vars:
    version: '3.1.5'
  tasks:
    - name: Ensure EPEL is enabled
      yum:
        name: epel-release
        state: present
      become: True
    - name: Ensure hostname is properly set
      hostname:
        name: '{{ inventory_hostname }}' 
      become: True
    - name: Ensure Ansible Tower installer is present
      get_url:
        url: 'http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ version }}.tar.gz'
        dest: '/tmp/ansible-tower-setup-{{ version }}.tar.gz'
    - name: Ensure unarchived version of Tower is present
      unarchive:
        remote_src: True
        src: '/tmp/ansible-tower-setup-{{ version }}.tar.gz'
        dest: /tmp
    - name: Ensure inventory file is properly located
      copy:
        remote_src: True
        dest: '/tmp/ansible-tower-setup-{{ version }}/inventory'
        src: /vagrant/inventory
    - name: Run the Ansible Tower installer
      shell: ./setup.sh
      args:
        chdir: '/tmp/ansible-tower-setup-{{ version }}'
      become: True
