N = 3
Vagrant::configure("2") do |config|
    ssh_pub_key = File.readlines("/home/fale/.ssh/id_rsa.pub").first.strip
    config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false

    config.vm.provider :libvirt do |v|
        v.qemu_use_session = false
    end
    config.vm.define "ansible" do |machine|
        machine.vm.box = "centos/8"
        machine.vm.hostname = "ansible"
        machine.vm.network "private_network", ip: "192.168.100.10"
    end
    (0..N-1).each do |machine_id|
        config.vm.box = "centos/8"
        config.vm.define "server#{machine_id}" do |machine|
            machine.vm.hostname = "server#{machine_id}"
            machine.vm.network "private_network", ip: "192.168.100.#{20+machine_id}"
        end
    end
end
