Vagrant.configure(2) do |config|

    # Set machine size
    config.vm.provider :libvirt do |domain|
        domain.memory = 2048
        domain.cpus = 2
    end

    # Test machine
    config.vm.define "test1" do |test1|
        test1.vm.box = "centos/7"
    end

end
