Vagrant.configure(2) do |config|

    # Set machine size
    config.vm.provider :libvirt do |domain|
        domain.memory = 512
        domain.cpus = 1
    end

    # Test machine 1
    config.vm.define "test1" do |test1|
        test1.vm.box = "centos/7"
    end

    # Test machine 2
    config.vm.define "test2" do |test2|
        test2.vm.box = "centos/7"
    end

    # Test machine 3
    config.vm.define "test3" do |test3|
        test3.vm.box = "centos/7"
    end

    # Test machine 4
    config.vm.define "test4" do |test4|
        test4.vm.box = "centos/7"
    end

end
