Vagrant.configure(2) do |config|

    # Set machine size
    config.vm.provider :libvirt do |domain|
        domain.memory = 2048
        domain.cpus = 1
    end

    config.vm.define "ansible.redhat.fale.io" do |core|
        core.vm.box = "centos/7"
    end

    config.vm.define "s1.redhat.fale.io" do |s1|
        s1.vm.box = "centos/7"
    end

    config.vm.define "s2.redhat.fale.io" do |s2|
        s2.vm.box = "centos/7"
    end

    config.vm.define "s3.redhat.fale.io" do |s3|
        s3.vm.box = "centos/7"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yaml"
        ansible.groups = {
            "core" => ["ansible.redhat.fale.io"],
            "servers" => ["s[1:3].redhat.fale.io"],
    }
    end

end
